import { Container, Paper, Stack, Typography } from "@mui/material"
import { SectionStyle } from "../../Styles"
import SectionTitle from "../SectionTitle"
import { styled } from "@mui/material/styles";

// const dataAr = [
//     "العجوزه",
//     "الشرطه العجوزه",
//     "الصفا",
//     "معهد السكر",
//     "القصر العيني الفرنساوى",
//     "التطوير الجراحي",
//     "القصر العيني قسم 23",
//     "القصر العيني الحالات الحرجه",
//     "القصر العيني المنيل التخصصى",
//     "القصر العيني قسم 29 الشراء الموحد",
//     "القصر العيني قسم الاشعه التداخليه",
//     "القصر العيني الاطفال الياباني",
//     "السلام المهندسين",
//     "كارديوتك",
//     "تامين صحي 6 اكتوبر",
//     "المقاولون العرب",
//     "مصر الدولى",
//     "دار الفؤاد 6 اكتوبر",
//     "مركز مصر للقسطره",
//     "الحياة",
//     "رابعة",
//     "الثريا",
//     "ويل كير",
//     "الامل والحياة",
//     "ايريس",
//     "معهد القلب",
//     "المروة",
//     "الصفوة اكتوبر",
//     "جامعة 6 اكتوبر",
//     "الشيخ زابد التخصصي",
//     "جامعة مصر",
//     "مصطفى محمود",
//     "نيورسباين",
//     "نيوروسبيتاليا",
//     "الوادي",
//     "جلوبال",
//     "هيفين اكتوبر",
//     "السلام الدولي",
//     "اندلسية",
//     "دار السلام",
//     "لايف كاث",
//     "كايروكاث",
//     "العاصمه كابيتال",
//     "النيل البدراوي",
//     "مبرة مصر القديمه",
//     "الشروق",
//     "الهلال العاملين المدنيين",
//     "العاملين المدنيين الكورنيش",
//     "الكاتب",
//     "ابن سينا",
//     "نيوهارت المعلمين",
//     "علاء عزت",
//     "الياسمين",
//     "جولدن هارت",
//     "عيادات شفا المعادي",
//     "ميلينيوم",
//     "جنه",
//     "شريان",
//     "الجزيره",
//     "مستشقى الهرم",
//     "السعودي الالماني",
//     "الدره",
//     "الايطالي",
//     "القطاميه كلينك",
//     "الصفوة",
//     "مركز قلب الاسماعيليه هشام حجازي",
//     "الراعي الصالح",
//     "وادى الطب",
//     "شفا التجمع",
//     "السكه الحديد",
//     "مصر للطيران",
//     "الجوي التخصصى",
//     "الناس",
//     "فلسطين",
//     "كارديو قنال",
//     "العقاد",
//     "المركز الطبي العالمي",
//     "النزهه الدولي",
//     "دار الشفا",
//     "كايرو هيلث كير",
//     "وادى النيل",
//     "الحياة",
//     "كليوباترا",
//     "القاهره التخصصي",
//     "السلام الدولي التجمع",
//     "نسائم",
//     "المطريه",
//     "بريمير التجمع",
//     "فريد حبيب",
//     "هليوبولس",
//     "كوبري القبه",
//     "الجلاء العسكري",
//     "العاملين الكورنيش",
//     "تامين صحى مدينة نصر",
//     "انتاج حربي",
//     "تاون",
//     "عين شمس التخصصى",
//     "وادى النيل",
//     "الكهرباء",
//     "الشرطة العجوزة",
//     "ايليت هارتن",
//     "حلوان التخصصى",
//     "تيودوربلهارس",
//     "النصر حلوان"
// ]

const data = [
    "Agouza",
    "Agouza Police",
    "Al-Safa",
    "Diabetes Institute",
    "Kasr Al-Aini French",
    "Surgical Development",
    "Kasr Al-Aini Department 23",
    "Kasr Al-Aini Critical Cases",
    "Kasr Al-Aini Al-Manial Specialized",
    "Kasr Al-Aini Department 29 Unified Procurement",
    "Kasr Al-Aini Interventional Radiology Department",
    "Kasr Al-Aini Japanese Children's Hospital",
    "Salam Mohandessin",
    "CardioTech",
    "Health Insurance 6th of October",
    "Arab Contractors",
    "Misr International",
    "Dar Al Fouad 6th of October",
    "Misr Catheterization Center",
    "Al-Hayah",
    "Rabaa",
    "Al-Thuraya",
    "Well Care",
    "Al-Amal and Al-Hayah",
    "Iris",
    "Heart Institute",
    "Al-Marwa",
    "Al-Safwa 6th of October",
    "6th of October University",
    "Sheikh Zayed Specialized",
    "Misr University",
    "Mostafa Mahmoud",
    "Neurospine",
    "Neurohospitalia",
    "Al-Wadi",
    "Global",
    "Heaven 6th of October",
    "Salam International",
    "Andalusia",
    "Dar Al Salam",
    "Life Cath",
    "CairoCath",
    "Capital City",
    "Nile Badrawi",
    "Mabra Old Egypt",
    "Al-Shorouk",
    "Hilal Civilian Employees",
    "Civilian Employees Corniche",
    "Al-Kateb",
    "Ibn Sina",
    "New Heart Teachers",
    "Alaa Ezzat",
    "Al-Yasmeen",
    "Golden Heart",
    "Shefa Clinics Maadi",
    "Millennium",
    "Jannah",
    "Sharian",
    "Al-Jazira",
    "Al-Haram Hospital",
    "Saudi German",
    "Al-Dorra",
    "Italian Hospital",
    "Katameya Clinic",
    "Al-Safwa",
    "Ismailia Heart Center Hisham Hegazy",
    "The Good Shepherd",
    "Wadi Al-Tibb",
    "Shefa Al-Tagamoa",
    "Railway Hospital",
    "EgyptAir Hospital",
    "Air Force Specialized",
    "Al-Nas",
    "Palestine",
    "Cardio Canal",
    "Al-Aqqad",
    "International Medical Center",
    "Nozha International",
    "Dar Al Shifa",
    "Cairo Healthcare",
    "Wadi Al-Nile",
    "Al-Hayah",
    "Cleopatra",
    "Cairo Specialized",
    "Salam International Al-Tagamoa",
    "Nasaem",
    "Al-Matariyah",
    "Premier Al-Tagamoa",
    "Farid Habib",
    "Heliopolis",
    "Kobri Al-Qubba",
    "Al-Galaa Military",
    "Civilian Employees Corniche",
    "Health Insurance Nasr City",
    "Military Production",
    "Town Hospital",
    "Ain Shams Specialized",
    "Wadi Al-Nile",
    "Electricity Hospital",
    "Agouza Police",
    "Elite Heart",
    "Helwan Specialized",
    "Theodor Bilharz",
    "Al-Nasr Helwan"
]

const PaperStyle = styled(Paper)(({ theme }) => ({
    border: `1px solid ${theme.palette.secondary.main}`,
    "&:hover": {
        backgroundColor: theme.palette.background.paper,
    },
}));

const Clients = () => {
    return (
        <SectionStyle id="clients">
            <SectionTitle sectionTitle='Clients' />
            <Container>
                <Stack direction={"row"} gap={2} flexWrap={"wrap"} justifyContent={"center"}>
                    {data.map((client, index) => (
                        <PaperStyle key={index}>
                            <Stack p={2}>
                                <Typography fontSize={16} fontWeight={"bold"}>
                                    {client}
                                </Typography>
                            </Stack>
                        </PaperStyle>
                    ))}
                </Stack>
            </Container>
        </SectionStyle>
    )
}

export default Clients